### ISSUE TITLE
Doesn't Disable Highlighting on Medium Derivatives

### ISSUE THREAD

**Issue by kashev** [KNNCreative/medium-hilight-off#1]
The extension works for urls which match `medium.com/*`, but it would be cool if it could also work on websites which are published using Medium on different URLs. Some examples:
- [`backchannel.com`](backchannel.com)
- [`theringer.com`](theringer.com)
- [`theawl.com`](theawl.com)
- [`thecauldron.si.com`](thecauldron.si.com)

It would be impossible to find them all. A possible fix might be to allow for the extension to access data on all websites, and detect somehow if they're medium based, or to allow configuration which can allow users to add URL matching patterns they need.

**Comment by kpx-dev** [comment]
@kashev Good catch. I'll try to implement based on your suggestion.

**Comment by kpx-dev** [comment]
@kashev fixed in https://github.com/KNNCreative/medium-highlight-off/commit/2d4dd3f007ca4df1fcb3848f8ed4f64a8d7a98e7
